frame_source: C:\Users\bruno\Desktop\Projetos UIoT\crowd_detector\crowd_detector\testimages\shopping.jpg

number_of_frames: 210
fetch_interval: 3
max_tries: 3

filename: crowd{}.jpg
foldername: result_images

reports_filename: reports.json

log_level: debug
